# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcnum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='number',
            field=models.IntegerField(),
        ),
    ]
