# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-30 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcnum', '0002_auto_20180130_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
